//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restorant_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUYURULABLOGLAR
    {
        public DUYURULABLOGLAR()
        {
            this.DUYURUBLOGYORUMLARI = new HashSet<DUYURUBLOGYORUMLARI>();
        }
    
        public int DuyuruID { get; set; }
        public string Baslik { get; set; }
        public string Icerik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Resim { get; set; }
        public string Yazar { get; set; }
        public bool Durum { get; set; }
    
        public virtual ICollection<DUYURUBLOGYORUMLARI> DUYURUBLOGYORUMLARI { get; set; }
    }
}
