//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restorant_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUYURUBLOGYORUMLARI
    {
        public int YorumID { get; set; }
        public Nullable<int> DuyuruID { get; set; }
        public string MusteriAdSoyad { get; set; }
        public string Mail { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string YorumMetni { get; set; }
        public bool Durum { get; set; }
    
        public virtual DUYURULABLOGLAR DUYURULABLOGLAR { get; set; }
    }
}
