//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restorant_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICERIKLER
    {
        public int IcerikID { get; set; }
        public string Baslik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string IcerikMetni { get; set; }
        public string Dosya { get; set; }
        public bool Durum { get; set; }
    }
}
