//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restorant_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KATEGORILER
    {
        public KATEGORILER()
        {
            this.URUNLER = new HashSet<URUNLER>();
        }
    
        public int KategoriID { get; set; }
        public string KategoriAd { get; set; }
        public string Resim { get; set; }
    
        public virtual ICollection<URUNLER> URUNLER { get; set; }
    }
}
