//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restorant_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASALAR
    {
        public MASALAR()
        {
            this.REZARVASYONLAR = new HashSet<REZARVASYONLAR>();
        }
    
        public int MasaID { get; set; }
        public int MasaNo { get; set; }
        public bool Durum { get; set; }
        public Nullable<int> Kapasite { get; set; }
    
        public virtual ICollection<REZARVASYONLAR> REZARVASYONLAR { get; set; }
    }
}
