//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restorant_Sitesi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WRestourantDBEntities : DbContext
    {
        public WRestourantDBEntities()
            : base("name=WRestourantDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ANASAYFA> ANASAYFA { get; set; }
        public DbSet<KATEGORILER> KATEGORILER { get; set; }
        public DbSet<MASALAR> MASALAR { get; set; }
        public DbSet<REZARVASYONDURUM> REZARVASYONDURUM { get; set; }
        public DbSet<REZARVASYONLAR> REZARVASYONLAR { get; set; }
        public DbSet<SEFLER> SEFLER { get; set; }
        public DbSet<URUNLER> URUNLER { get; set; }
        public DbSet<USTILETISIM> USTILETISIM { get; set; }
        public DbSet<YORUMLAR> YORUMLAR { get; set; }
        public DbSet<HAKKIMDA> HAKKIMDA { get; set; }
        public DbSet<NAVBAR> NAVBAR { get; set; }
        public DbSet<SIFRE_SIFIRLAMA> SIFRE_SIFIRLAMA { get; set; }
        public DbSet<SITE_AYARLARI> SITE_AYARLARI { get; set; }
        public DbSet<UYELER> UYELER { get; set; }
        public DbSet<ICERIKLER> ICERIKLER { get; set; }
        public DbSet<DUYURUBLOGYORUMLARI> DUYURUBLOGYORUMLARI { get; set; }
        public DbSet<DUYURULABLOGLAR> DUYURULABLOGLAR { get; set; }
    }
}
