//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restorant_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAVBAR
    {
        public int NavbarID { get; set; }
        public string MenuAd { get; set; }
        public string Link { get; set; }
        public Nullable<int> Sira { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
