//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restorant_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REZARVASYONLAR
    {
        public int RezervasyonID { get; set; }
        public Nullable<int> MasaID { get; set; }
        public string MusteriAdSoyad { get; set; }
        public string Mail { get; set; }
        public string MusteriTelefon { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.TimeSpan> Saat { get; set; }
        public int KisiSayisi { get; set; }
        public Nullable<int> DurumID { get; set; }
    
        public virtual MASALAR MASALAR { get; set; }
        public virtual REZARVASYONDURUM REZARVASYONDURUM { get; set; }
    }
}
