//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restorant_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEFLER
    {
        public int SefID { get; set; }
        public string Resim { get; set; }
        public string SefAdSoyad { get; set; }
        public string Uzmanlik { get; set; }
        public string Aciklama { get; set; }
        public bool Durum { get; set; }
    }
}
