//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restorant_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIFRE_SIFIRLAMA
    {
        public int TalepID { get; set; }
        public Nullable<int> UyeID { get; set; }
        public string SifirlamaKodu { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public System.DateTime GecerlilikTarihi { get; set; }
        public Nullable<bool> KullanildiMi { get; set; }
    
        public virtual UYELER UYELER { get; set; }
    }
}
