//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restorant_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBELER
    {
        public int SubeID { get; set; }
        public string SubeAd { get; set; }
        public string Sehir { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    }
}
