//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restorant_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUNLER
    {
        public int UrunID { get; set; }
        public string UrunAd { get; set; }
        public decimal Fiyat { get; set; }
        public string Icindekiler { get; set; }
        public string Resim { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual KATEGORILER KATEGORILER { get; set; }
    }
}
