//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restorant_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USTILETISIM
    {
        public int UstID { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string AcilisKapanis { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
        public string Twitter { get; set; }
        public string Linkedin { get; set; }
        public bool Durum { get; set; }
    }
}
