//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restorant_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UYELER
    {
        public UYELER()
        {
            this.SIFRE_SIFIRLAMA = new HashSet<SIFRE_SIFIRLAMA>();
        }
    
        public int UyeID { get; set; }
        public string AdSoyad { get; set; }
        public string Mail { get; set; }
        public string Sifre { get; set; }
        public string Yetki { get; set; }
        public Nullable<bool> SozlesmeOnay { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual ICollection<SIFRE_SIFIRLAMA> SIFRE_SIFIRLAMA { get; set; }
    }
}
